/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

module soc_top(clk, rst_n, paddr, pwrite, psel, penable, pwdata, prdata);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input clk;
  wire clk;
  wire \dout1[0] ;
  wire \dout1[10] ;
  wire \dout1[11] ;
  wire \dout1[12] ;
  wire \dout1[13] ;
  wire \dout1[14] ;
  wire \dout1[15] ;
  wire \dout1[16] ;
  wire \dout1[17] ;
  wire \dout1[18] ;
  wire \dout1[19] ;
  wire \dout1[1] ;
  wire \dout1[20] ;
  wire \dout1[21] ;
  wire \dout1[22] ;
  wire \dout1[23] ;
  wire \dout1[24] ;
  wire \dout1[25] ;
  wire \dout1[26] ;
  wire \dout1[27] ;
  wire \dout1[28] ;
  wire \dout1[29] ;
  wire \dout1[2] ;
  wire \dout1[30] ;
  wire \dout1[31] ;
  wire \dout1[3] ;
  wire \dout1[4] ;
  wire \dout1[5] ;
  wire \dout1[6] ;
  wire \dout1[7] ;
  wire \dout1[8] ;
  wire \dout1[9] ;
  input [31:0] paddr;
  wire [31:0] paddr;
  input penable;
  wire penable;
  output [31:0] prdata;
  wire [31:0] prdata;
  input psel;
  wire psel;
  input [31:0] pwdata;
  wire [31:0] pwdata;
  input pwrite;
  wire pwrite;
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__conb_1 _4_ (
    .HI(_0_)
  );
  sky130_fd_sc_hd__conb_1 _5_ (
    .HI(_1_)
  );
  sky130_fd_sc_hd__conb_1 _6_ (
    .HI(_2_)
  );
  sky130_fd_sc_hd__conb_1 _7_ (
    .HI(_3_)
  );
  sky130_sram_1kbyte_1rw1r_32x256_8 u_sram (
    .clk0(clk),
    .clk1(clk),
    .dout0(prdata),
    .dout1({ \dout1[31] , \dout1[30] , \dout1[29] , \dout1[28] , \dout1[27] , \dout1[26] , \dout1[25] , \dout1[24] , \dout1[23] , \dout1[22] , \dout1[21] , \dout1[20] , \dout1[19] , \dout1[18] , \dout1[17] , \dout1[16] , \dout1[15] , \dout1[14] , \dout1[13] , \dout1[12] , \dout1[11] , \dout1[10] , \dout1[9] , \dout1[8] , \dout1[7] , \dout1[6] , \dout1[5] , \dout1[4] , \dout1[3] , \dout1[2] , \dout1[1] , \dout1[0]  }),
    .wmask0({ _3_, _2_, _1_, _0_ })
  );
endmodule
